routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware([\App\Http\Middleware\Authenticate::class])->group(function () {

//   dashboard
    Route::get('/', [\App\Http\Controllers\DashboardController::class, 'index'])->name('index');
    Route::get('filterProduk/{produkname}', [\App\Http\Controllers\DashboardController::class, 'filterProduk'])->name('filter.produk');
    Route::get('filterStock/{bahanname}', [\App\Http\Controllers\DashboardController::class, 'filterStok'])->name('filter.stok');
    Route::post('insert-update-invoice', [\App\Http\Controllers\DashboardController::class, 'bayar'])->name('bayar');
    Route::post('bayar', [\App\Http\Controllers\DashboardController::class, 'applyBayar'])->name('bayar-apply');
    Route::get('print/invoice/{noinvoice}', [\App\Http\Controllers\PrintController::class, 'printInvoice'])->name('print.invoice');
    Route::get('invoice/dataTable', [\App\Http\Controllers\DashboardController::class, 'invoiceList'])->name('invoice.dataTable');
    Route::get('invoice/detail/{noinvoice}',[\App\Http\Controllers\DashboardController::class,'invoiceDetail'])->name('invoice.detail');
    Route::get('invoice/detailJs/{noinvoice}',[\App\Http\Controllers\DashboardController::class,'invoiceDetailJs'])->name('invoice.detailJs');

//    barang
    Route::get('barang', [\App\Http\Controllers\BarangController::class, 'index'])->name('barang');
    Route::get('barang/bahan-selection', [\App\Http\Controllers\BarangController::class, 'bahanSelection'])->name('barang.bahan.selection');

    Route::get('master/bahan/logs',[\App\Http\Controllers\BarangController::class,'stokLogs'])->name('bahan.logs');
    Route::get('master/bahan/dataTable', [\App\Http\Controllers\Master\BahanController::class, 'dataTable'])->name('bahan.dataTable');
    Route::resource('master/bahan', \App\Http\Controllers\Master\BahanController::class);

    Route::resource('master/produk/receipt', \App\Http\Controllers\ProdukJualController::class);
    Route::get('master/produk/receipt/dataTable/{produk_id}', [\App\Http\Controllers\ProdukJualController::class, 'dataTable']);
    Route::resource('master/produk', \App\Http\Controllers\Master\ProdukController::class);

//    laporan
    Route::post('report-management/pembukuan/update',[\App\Http\Controllers\Laporan\PembukuanController::class,'updatePembukuan'])->name('pembukuan.update');
    Route::get('report-management/pembukuan/get-all-buku',[\App\Http\Controllers\Laporan\PembukuanController::class,'getAllBuku'])->name('pembukuan.getAllBuku');
    Route::get('report-management/pembukuan/get-all-buku-monthy/{monthy}',[\App\Http\Controllers\Laporan\PembukuanController::class,'getAllBukuPerMonth'])->name('pembukuan.getMonthyBuku');
    Route::get('report-management/pembukuan/generate',[\App\Http\Controllers\Laporan\PembukuanController::class,'generatePembukuan'])->name('pembukuan.generate');
    Route::get('report-management/pembukuan/check',[\App\Http\Controllers\Laporan\PembukuanController::class,'checkPembukuan'])->name('pembukuan.check');
    Route::get('report-management/pembukuan/tfoot/{monthy}',[\App\Http\Controllers\Laporan\PembukuanController::class,'tfootPembukuan'])->name('pembukuan.tfoot');
    Route::get('report-management/pembukuan/DataTable',[\App\Http\Controllers\Laporan\PembukuanController::class,'pembukuanDatatable'])->name('pembukuan.dataTable');
    Route::get('report-management/chartTahunan',[\App\Http\Controllers\Laporan\LaporanController::class,'chartTahunan'])->name('report.chartTahunan');
    Route::get('report-management', [\App\Http\Controllers\Laporan\LaporanController::class, 'hariIni'])->name('report.today');
    Route::get('report-management/laporan', [\App\Http\Controllers\Laporan\LaporanController::class, 'index'])->name('laporan.index');

//    settings
    Route::get('settings', [\App\Http\Controllers\SettingController::class, 'index'])->name('settings');

    Route::get('master/toko/dataTable', [\App\Http\Controllers\Master\TokoController::class, 'dataTable'])->name('toko.dataTable');
    Route::resource('master/toko', \App\Http\Controllers\Master\TokoController::class);

    Route::get('master/role/dataTable', [\App\Http\Controllers\User\RoleController::class, 'dataTable'])->name('role.dataTable');
    Route::resource('master/role', \App\Http\Controllers\User\RoleController::class);

    Route::get('user-management/users/profile-settings', [\App\Http\Controllers\User\UserController::class, 'profileView'])->name('profile.index');
    Route::post('user-management/users/profile-settings-process', [\App\Http\Controllers\User\UserController::class, 'profileProcess'])->name('profile.process');
    Route::get('user-management/users/getSelectedData', [\App\Http\Controllers\User\UserController::class, 'getSelectData'])->name('user.selected.data');
    Route::get('user-management/users/password', [\App\Http\Controllers\User\UserController::class, 'passwordView'])->name('password.index');
    Route::post('user-management/users/passwordprocess', [\App\Http\Controllers\User\UserController::class, 'passwordProcess'])->name('password.process');
    Route::resource('user-management/role', \App\Http\Controllers\User\RoleController::class);
    Route::resource('user-management/users', \App\Http\Controllers\User\UserController::class);

});


Route::get('login', [\App\Http\Controllers\LoginController::class, 'index'])->name('login');
Route::get('logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');
Route::post('login/process', [\App\Http\Controllers\LoginController::class, 'loginProcess'])->name('login.process');
//Route::get('landing',[\App\Http\Controllers\LoginController::class,'landing'])->name('landing');

app/Models/Master/Bahan.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bahan extends Model
{
    protected $fillable=['nama','quantity','harga','image_uri'];
    use HasFactory;
}

app/Models/Master/Produk.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    protected $fillable=['nama','harga_jual','harga_modal','image_uri','toko_id'];
    use HasFactory;

    public function toko(){
        return $this->belongsTo(Toko::class);
    }
}

app/Models/Master/Toko.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Toko extends Model
{
    use HasFactory;
    protected $fillable=['nama','logos_uri'];
}

app/Http/Controllers/Master/BahanController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Models\Logs\StokLog;
use App\Models\Master\Bahan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Yajra\DataTables\Facades\DataTables;

class BahanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Bahan::all();
        return view('admin.master.bahan.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = $request->file('logo');
        $fileName = "";
        if ($image) {
            $fileName = time() . '.' . $image->getClientOriginalExtension();
            $img = Image::make($image->getRealPath());
            $img->resize(120, 120, function ($constraint) {
                $constraint->aspectRatio();
            });

            $img->save(public_path('storage/images/imageBahan/small/'). $fileName);
            $image->move(public_path('storage/images/imageBahan/big/',$fileName));

//            $img->stream(); // <-- Key point
//            Storage::disk('local')->put('public/images/imageBahan/small' . '/' . $fileName, $img, 'public');
//            Storage::disk('local')->put('public/images/imageBahan/big' . '/' . $fileName, file_get_contents($image->getRealPath()), 'public');
        }

        $data = Bahan::create(['nama' => $request->nama, 'harga' => 0, 'quantity' => $request->quantity, 'image_uri' => $fileName]);
        return redirect()->route('bahan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $toUpdate = Bahan::find($id);

        $aksi = ($toUpdate->quantity > $request->quantity ? 2 : 1);
        $qtySebelumUpdate =  $toUpdate->quantity;
        $aksiQuantity = abs($toUpdate->quantity - $request->quantity);

        $toUpdate->nama = $request->nama;
        $toUpdate->harga = 0;
        $toUpdate->quantity = $request->quantity;

        $image = $request->file('logo');
        if ($image) {
            $fileName = time() . '.' . $image->getClientOriginalExtension();
            $img = Image::make($image->getRealPath());
            $img->resize(120, 120, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save(public_path('storage/images/imageBahan/small/'). $fileName);
            $image->move(public_path('storage/images/imageBahan/big/',$fileName));

//            $img->stream(); // <-- Key point
//            Storage::disk('local')->put('public/images/imageBahan/small' . '/' . $fileName, $img, 'public');
//            Storage::disk('local')->put('public/images/imageBahan/big' . '/' . $fileName, file_get_contents($image->getRealPath()), 'public');
            $toUpdate->image_uri = $fileName;
        }
        $toUpdate->save();


        $user = Auth::user();

        $stokLog = StokLog::create([
            'bahan_id'=>$toUpdate->id,
            'aksi_quantity'=>$aksiQuantity,
            'aksi'=>$aksi,
            'sebelum_quantity'=>$qtySebelumUpdate,
            'final_quantity'=>$toUpdate->quantity,
            'produk_id'=>-1,
            'toko_id'=>$user['toko_id'],
            'user_id'=>$user['id']
        ]);

        return response('success',200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Bahan::find($id)->delete();
        return response('success delete', 200);
        //
    }

    public function dataTable(){
        return DataTables::eloquent(Bahan::query())
            ->editColumn('image',function($data){

                return  ($data->image_uri == "" ? '<img src="'.asset("original-asset/no-photo.jpg").'" alt="" height="120" width="120">   ' : '<img src="'.asset("storage/images/imageBahan/small")."/".$data->image_uri.'" alt="" height="120" width="120"> ');
            })
            ->editColumn('action',function ($data){
                return " <button class='btn btn-info' data-toggle='modal' data-target='#modalEditBahan' data-json='".json_encode($data)."'><i class='fa fa-pencil'></i>
                                                        </button>
                                                        <button class='btn btn-danger' data-toggle='modal'
                                                                data-target='#modalDeleteBahan' data-json='".json_encode($data)."'><i
                                                                class='fa fa-trash'></i></button>";
            })
            ->rawColumns(['image', 'action'])
            ->make(true);
    }
}

app/Http/Controllers/Master/ProdukController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Models\Master\Bahan;
use App\Models\Master\Produk;
use App\Models\ProdukJual;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataProduk = Produk::all();
        $dataBahan = Bahan::all();
        $data = [
            'dataProduk' => $dataProduk,
            'dataBahan' => $dataBahan
        ];
        return view('admin.master.produk.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = $request->file('logo');
        $fileName = "";
        if ($image) {
            $fileName = time() . '.' . $image->getClientOriginalExtension();
            $img = Image::make($image->getRealPath());
            $img->resize(120, 120, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save(public_path('storage/images/imageProduk/small/'). $fileName);
            $image->move(public_path('storage/images/imageProduk/big/',$fileName));

            //ini untuk yg pakai storage
//            $img->stream(); // <-- Key point
//            Storage::disk('local')->put('public/images/imageProduk/small' . '/' . $fileName, $img, 'public');
//            Storage::disk('local')->put('public/images/imageProduk/big' . '/' . $fileName, file_get_contents($image->getRealPath()), 'public');

        }
        $data = Produk::create([
            'nama' => $request->nama,
            'harga_jual' => $request->harga_jual,
            'harga_modal' => $request->harga_modal,
            'image_uri' => $fileName,
            'toko_id'=>$request->toko_id
        ]);
//        return redirect(route('produk.index'));
        return redirect()->route('barang');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $toUpdate = Produk::find($id);
        $toUpdate->nama = $request->nama;
        $toUpdate->harga_jual = $request->harga_jual;
        $toUpdate->harga_modal = $request->harga_modal;
        $toUpdate->toko_id = $request->toko_id;
        $image = $request->file('logo');
        if ($image) {
            $fileName = time() . '.' . $image->getClientOriginalExtension();
            $img = Image::make($image->getRealPath());
            $img->resize(120, 120, function ($constraint) {
                $constraint->aspectRatio();
            });

            $img->save(public_path('storage/images/imageProduk/small/'). $fileName);
            $image->move(public_path('storage/images/imageProduk/big/',$fileName));

//            $img->stream(); // <-- Key point
//            Storage::disk('local')->put('public/images/imageProduk/small' . '/' . $fileName, $img, 'public');
//            Storage::disk('local')->put('public/images/imageProduk/big' . '/' . $fileName, file_get_contents($image->getRealPath()), 'public');
            $toUpdate->image_uri = $fileName;
        }

        $toUpdate->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Produk::find($id)->delete();
        ProdukJual::where('produk_id',$id)->delete();
        return response('success delete', 200);
        //
    }
}

resources/views/admin/master/toko/index.blade.php
@extends('layout.main')
@section('css')
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Master Toko</h4>
                </div>
                <div class="card-content">
                    <div class="card-body card-dashboard">
                            <p class="card-text">Tambah toko</p>
                        <button class="btn btn-primary" data-toggle="modal" data-target="#modalAddToko">Tambah Toko</button>
                        <div class="table-responsive">
                            <table class="table zero-configuration2 table-striped table-bordered     ">
                                <thead>
                                <tr>
                                    <th class="text-center">Nama</th>
                                    <th class="text-center">Logo</th>
                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($data as $dt)
                                    <tr>
                                        <td class="text-center">{{$dt->nama}}</td>
                                        <td class="text-center"><img
                                                src="{{asset('storage/images/logostoko/small').'/'.$dt->logos_uri}}"
                                                alt=""></td>
                                        <td class="text-center">
                                            <button class="btn btn-info" data-toggle="modal" data-target="#modalEditToko"
                                                    data-json='{{json_encode($dt)}}'><i class="fa fa-pencil"></i>
                                            </button>
                                            <button class="btn btn-danger" data-toggle="modal"
                                                    data-target="#modalDeleteToko" data-json='{{json_encode($dt)}}'><i
                                                    class="fa fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- Modal -->
    <div class="modal fade" id="modalAddToko" tabindex="-1" role="dialog" aria-labelledby="modalAdd" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Nama Toko</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('toko.store')}}" enctype="multipart/form-data" method="post">
                    <div class="modal-body">
                        @csrf
                        <label>Nama Toko: </label>
                        <div class="form-group">
                            <input type="text" placeholder="Nama Toko" name="nama" class="form-control">
                        </div>

                        <label>Logo Toko: </label>
                        <div class="form-group">
                            <input type="file" placeholder="file" name="logo" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalEditToko" tabindex="-1" role="dialog" aria-labelledby="modalAdd" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Nama Toko</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="javascript:void(0)" id="edit-formToko" enctype="multipart/form-data" method="post">
                    <div class="modal-body">
                        @csrf
                        @method('PUT')
                        <label>Nama Toko: </label>
                        <div class="form-group">
                            <input type="text" id="editnameToko" placeholder="Nama Toko" name="nama" class="form-control">
                        </div>

                        <label>Logo Toko: </label>
                        <div class="form-group">
                            <input type="file" id="editlogosuriToko" placeholder="file" name="logo" class="form-control">
                        </div>
                        <input type="text" name="id" id="editidToko" hidden>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Ubah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalDeleteToko" tabindex="-1" role="dialog" aria-labelledby="modalAdd" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Delete Toko</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="javascript:void(0)" id="delete-formToko" enctype="multipart/form-data" method="post">
                    <div class="modal-body">
                        @method('delete')
                        @csrf
                        <p>Apakah kamu yakin ingin hapus toko ?</p>
                        <input type="text" id="deleteidToko" name="id" hidden>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">Ya</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
{{--    <script src="{{asset('assets')}}/vendors/js/tables/datatable/pdfmake.min.js"></script>--}}
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/vfs_fonts.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/datatables.buttons.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/buttons.html5.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/buttons.print.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/buttons.bootstrap.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/datatables.bootstrap4.min.js"></script>
    {{--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>--}}

    <script>

        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('.zero-configuration2').DataTable({
            });
            $('#modalDeleteToko').on('show.bs.modal', function (e) {
                {{--    oTable.ajax.reload(null, false);--}}
                let data = $(e.relatedTarget).data('json');
                $('#deleteidToko').val(data.id.toString());
            });
            $('#modalEditToko').on('show.bs.modal', function (e) {
                {{--    oTable.ajax.reload(null, false);--}}
                let data = $(e.relatedTarget).data('json');

                $('#editidToko').val(data.id.toString());
                $('#editnameToko').val(data.nama.toString());

            });
            $('#delete-formToko').submit(function (e) {
                e.preventDefault();
                var formData = new FormData(this);
                let Id = formData.get('id');
                $.ajax({
                    url: '{{env('APP_URL')}}/master/toko/' + Id,
                    type: 'DELETE',
                    dataType: 'HTML',
                    success: function (resp) {
                        $("#modalDeleteToko").modal("hide");
                        location.reload()
                    },
                    error: function (data) {
                        console.log(data);
                    }
                });
            });

            $('#edit-formToko').submit(function (e) {
                e.preventDefault();
                var formData = new FormData(this);
                let Id = formData.get('id');
                $.ajax({
                    type: 'POST',
                    url: "{{env('APP_URL')}}/master/toko/" + Id,
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: (data) => {
                        // this.reset();
                        $('#modalEditToko').modal('hide');
                        location.reload()
                        // oTable.ajax.reload(null, false);
                    },
                    error: function (data) {
                        // console.log(data);
                    }
                });
            });
        });
    </script>
@endsection