routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware([\App\Http\Middleware\Authenticate::class])->group(function () {

//   dashboard
    Route::get('/', [\App\Http\Controllers\DashboardController::class, 'index'])->name('index');
    Route::get('filterProduk/{produkname}', [\App\Http\Controllers\DashboardController::class, 'filterProduk'])->name('filter.produk');
    Route::get('filterStock/{bahanname}', [\App\Http\Controllers\DashboardController::class, 'filterStok'])->name('filter.stok');
    Route::post('insert-update-invoice', [\App\Http\Controllers\DashboardController::class, 'bayar'])->name('bayar');
    Route::post('bayar', [\App\Http\Controllers\DashboardController::class, 'applyBayar'])->name('bayar-apply');
    Route::get('print/invoice/{noinvoice}', [\App\Http\Controllers\PrintController::class, 'printInvoice'])->name('print.invoice');
    Route::get('invoice/dataTable', [\App\Http\Controllers\DashboardController::class, 'invoiceList'])->name('invoice.dataTable');
    Route::get('invoice/detail/{noinvoice}',[\App\Http\Controllers\DashboardController::class,'invoiceDetail'])->name('invoice.detail');
    Route::get('invoice/detailJs/{noinvoice}',[\App\Http\Controllers\DashboardController::class,'invoiceDetailJs'])->name('invoice.detailJs');

//    barang
    Route::get('barang', [\App\Http\Controllers\BarangController::class, 'index'])->name('barang');
    Route::get('barang/bahan-selection', [\App\Http\Controllers\BarangController::class, 'bahanSelection'])->name('barang.bahan.selection');

    Route::get('master/bahan/logs',[\App\Http\Controllers\BarangController::class,'stokLogs'])->name('bahan.logs');
    Route::get('master/bahan/dataTable', [\App\Http\Controllers\Master\BahanController::class, 'dataTable'])->name('bahan.dataTable');
    Route::resource('master/bahan', \App\Http\Controllers\Master\BahanController::class);

    Route::resource('master/produk/receipt', \App\Http\Controllers\ProdukJualController::class);
    Route::get('master/produk/receipt/dataTable/{produk_id}', [\App\Http\Controllers\ProdukJualController::class, 'dataTable']);
    Route::resource('master/produk', \App\Http\Controllers\Master\ProdukController::class);

//    laporan
    Route::post('report-management/pembukuan/update',[\App\Http\Controllers\Laporan\PembukuanController::class,'updatePembukuan'])->name('pembukuan.update');
    Route::get('report-management/pembukuan/get-all-buku',[\App\Http\Controllers\Laporan\PembukuanController::class,'getAllBuku'])->name('pembukuan.getAllBuku');
    Route::get('report-management/pembukuan/get-all-buku-monthy/{monthy}',[\App\Http\Controllers\Laporan\PembukuanController::class,'getAllBukuPerMonth'])->name('pembukuan.getMonthyBuku');
    Route::get('report-management/pembukuan/generate',[\App\Http\Controllers\Laporan\PembukuanController::class,'generatePembukuan'])->name('pembukuan.generate');
    Route::get('report-management/pembukuan/check',[\App\Http\Controllers\Laporan\PembukuanController::class,'checkPembukuan'])->name('pembukuan.check');
    Route::get('report-management/pembukuan/tfoot/{monthy}',[\App\Http\Controllers\Laporan\PembukuanController::class,'tfootPembukuan'])->name('pembukuan.tfoot');
    Route::get('report-management/pembukuan/DataTable',[\App\Http\Controllers\Laporan\PembukuanController::class,'pembukuanDatatable'])->name('pembukuan.dataTable');
    Route::get('report-management/chartTahunan',[\App\Http\Controllers\Laporan\LaporanController::class,'chartTahunan'])->name('report.chartTahunan');
    Route::get('report-management', [\App\Http\Controllers\Laporan\LaporanController::class, 'hariIni'])->name('report.today');
    Route::get('report-management/laporan', [\App\Http\Controllers\Laporan\LaporanController::class, 'index'])->name('laporan.index');

//    settings
    Route::get('settings', [\App\Http\Controllers\SettingController::class, 'index'])->name('settings');

    Route::get('master/toko/dataTable', [\App\Http\Controllers\Master\TokoController::class, 'dataTable'])->name('toko.dataTable');
    Route::resource('master/toko', \App\Http\Controllers\Master\TokoController::class);

    Route::get('master/role/dataTable', [\App\Http\Controllers\User\RoleController::class, 'dataTable'])->name('role.dataTable');
    Route::resource('master/role', \App\Http\Controllers\User\RoleController::class);

    Route::get('user-management/users/profile-settings', [\App\Http\Controllers\User\UserController::class, 'profileView'])->name('profile.index');
    Route::post('user-management/users/profile-settings-process', [\App\Http\Controllers\User\UserController::class, 'profileProcess'])->name('profile.process');
    Route::get('user-management/users/getSelectedData', [\App\Http\Controllers\User\UserController::class, 'getSelectData'])->name('user.selected.data');
    Route::get('user-management/users/password', [\App\Http\Controllers\User\UserController::class, 'passwordView'])->name('password.index');
    Route::post('user-management/users/passwordprocess', [\App\Http\Controllers\User\UserController::class, 'passwordProcess'])->name('password.process');
    Route::resource('user-management/role', \App\Http\Controllers\User\RoleController::class);
    Route::resource('user-management/users', \App\Http\Controllers\User\UserController::class);

});


Route::get('login', [\App\Http\Controllers\LoginController::class, 'index'])->name('login');
Route::get('logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');
Route::post('login/process', [\App\Http\Controllers\LoginController::class, 'loginProcess'])->name('login.process');
//Route::get('landing',[\App\Http\Controllers\LoginController::class,'landing'])->name('landing');

app/Models/User/Role.php
<?php

namespace App\Models\User;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $fillable=['nama'];
}

app/Http/Controllers/User/RoleController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\User\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Yajra\DataTables\Facades\DataTables;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Role::all();
        return view('admin.user-management.role.index',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $data = Role::create(['nama'=>$request->nama]);
//        return redirect(route('role.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $toUpdate = Role::find($id);
        $toUpdate->nama = $request->nama;


        $toUpdate->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Role::find($id)->delete();
        return response('success delete',200);
    }

    public function dataTable(){
       return DataTables::eloquent(Role::query())
           ->editColumn('action',function ($data){
               return " <button class='btn btn-info' data-toggle='modal' data-target='#modalEditRole'
                                                                data-json='".json_encode($data)."'><i class='fa fa-pencil'></i>
                                                        </button>
                                                        <button class='btn btn-danger' data-toggle='modal'
                                                                data-target='#modalDeleteRole' data-json='".json_encode($data)."'><i
                                                                class='fa fa-trash'></i></button>";
           })
           ->make(true);
    }

}

resources/views/admin/user-management/role/index.blade.php
@extends('layout.main')
@section('css')
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Master Role</h4>
                </div>
                <div class="card-content">
                    <div class="card-body card-dashboard">
                        <p class="card-text">Tambah Role</p>
                        <button class="btn btn-primary" data-toggle="modal" data-target="#modalAddRole">Tambah Role</button>
                        <div class="table-responsive">
                            <table class="table zero-configuration1 table-striped table-bordered     ">
                                <thead>
                                <tr>
                                    <th class="text-center">Nama</th>

                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($data as $dt)
                                    <tr>
                                        <td class="text-center">{{$dt->nama}}</td>
                                        <td class="text-center">
                                            <button class="btn btn-info" data-toggle="modal" data-target="#modalEditRole"
                                                    data-json='{{json_encode($dt)}}'><i class="fa fa-pencil"></i>
                                            </button>
                                            <button class="btn btn-danger" data-toggle="modal"
                                                    data-target="#modalDeleteRole" data-json='{{json_encode($dt)}}'><i
                                                    class="fa fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- Modal -->
    <div class="modal fade" id="modalAddRole" tabindex="-1" role="dialog" aria-labelledby="modalAdd" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Nama Role</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('role.store')}}" enctype="multipart/form-data" method="post">
                    <div class="modal-body">
                        @csrf
                        <label>Nama Role: </label>
                        <div class="form-group">
                            <input type="text" placeholder="Nama Role" name="nama" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalEditRole" tabindex="-1" role="dialog" aria-labelledby="modalAdd" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Nama Role</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="javascript:void(0)" id="edit-formRole" enctype="multipart/form-data" method="post">
                    <div class="modal-body">
                        @csrf
                        @method('PUT')
                        <label>Nama Role: </label>
                        <div class="form-group">
                            <input type="text" id="editnameRole" placeholder="Nama Role" name="nama" class="form-control">
                        </div>

                        <input type="text" name="id" id="editidRole" hidden>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Ubah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalDeleteRole" tabindex="-1" role="dialog" aria-labelledby="modalAdd" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Delete Role</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="javascript:void(0)" id="delete-formRole" enctype="multipart/form-data" method="post">
                    <div class="modal-body">
                        @method('delete')
                        @csrf
                        <p>Apakah kamu yakin ingin hapus Role ?</p>
                        <input type="text" id="deleteidRole" name="id" hidden>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">Ya</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
{{--    <script src="{{asset('assets')}}/vendors/js/tables/datatable/pdfmake.min.js"></script>--}}
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/vfs_fonts.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/datatables.buttons.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/buttons.html5.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/buttons.print.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/buttons.bootstrap.min.js"></script>
    <script src="{{asset('assets')}}/vendors/js/tables/datatable/datatables.bootstrap4.min.js"></script>
    {{--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>--}}

    <script>

        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('.zero-configuration1').DataTable({
            });
            $('#modalDeleteRole').on('show.bs.modal', function (e) {
                {{--    oTable.ajax.reload(null, false);--}}
                let data = $(e.relatedTarget).data('json');
                $('#deleteidRole').val(data.id.toString());
            });
            $('#modalEditRole').on('show.bs.modal', function (e) {
                {{--    oTable.ajax.reload(null, false);--}}
                let data = $(e.relatedTarget).data('json');

                $('#editidRole').val(data.id.toString());
                $('#editnameRole').val(data.nama.toString());

            });
            $('#delete-formRole').submit(function (e) {
                e.preventDefault();
                var formData = new FormData(this);
                let Id = formData.get('id');
                console.log(formData);
                $.ajax({
                    url: '{{env('APP_URL')}}/master/role/' + Id,
                    type: 'DELETE',
                    dataType: 'HTML',
                    success: function (resp) {
                        $("#modalDeleteRole").modal("hide");
                        location.reload()
                    },
                    error: function (data) {
                        console.log(data);
                    }
                });
            });

            $('#edit-formRole').submit(function (e) {
                e.preventDefault();
                var formData = new FormData(this);
                let Id = formData.get('id');
                console.log(formData);
                $.ajax({
                    type: 'POST',
                    url: "{{env('APP_URL')}}/master/role/" + Id,
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: (data) => {
                        // this.reset();
                        $('#modalEditRole').modal('hide');
                        location.reload()
                        // oTable.ajax.reload(null, false);
                    },
                    error: function (data) {
                        // console.log(data);
                    }
                });
            });
        });
    </script>
@endsection